### ISSUE TITLE
Sometimes GeneratePrivateKey() generates a hex string not 64 characters long

### ISSUE THREAD

**Issue by rolznz** [nbd-wtf/go-nostr#111]
https://github.com/nbd-wtf/go-nostr/blob/master/keys.go#L14C6-L14C24

If the hex starts with 00's they will be removed. Suggested solution (untested):
```
hexStr := hex.EncodeToString(k.Bytes())
return fmt.Sprintf("%064s", hexStr)
```

Supposedly this should be very rare, but I believe it's already happened to me twice.

**Comment by fiatjaf** [comment]
Thank you!
