### ISSUE TITLE
pool.SubMany goroutine leak

### ISSUE THREAD

**Issue by bndw** [nbd-wtf/go-nostr#118]
I'm using `SimplePool.SubMany` and explicitly canceling the context to avoid the risk of goroutine bloat, as per the [README](https://github.com/nbd-wtf/go-nostr/blob/master/README.md?plain=1#L119). However I'm noticing a memory leak in [my project](https://github.com/bndw/nostr-relay-proxy/issues/1) and pprof is pointing to go-nostr.

I dug into the `subMany` method and have confirmed [this](https://github.com/nbd-wtf/go-nostr/blob/master/pool.go#L203) is the point at which the context cancel is caught. The problem is, this path never invokes the [defer func](https://github.com/nbd-wtf/go-nostr/blob/master/pool.go#L120) above so the `events chan` is never closed. I wonder if leaking these event chans is the problem.

Here's how I'm using it [[actual source](https://github.com/bndw/nostr-relay-proxy/blob/bndw/nip42/relay.go#L93)]:
```go
// ctx is a context.WithTimeout
subscription = nostr.NewSimplePool(ctx).SubMany(ctx, someRelays, []nostr.Filter{filter})
```

Any ideas? Am I using the library incorrectly?

**Comment by bndw** [comment]
You are right, defer is being called. I missed in the dump of debug logs.

I'm using `context.WithTimeout` to cancel the subscription after a period of time.

I think this disproves my original theory for the memory leak, but the problem persists. I'm building a relay proxy. My client connects to this single relay and fans in/out events. pprof pointed to this [wsflate.Reader](https://github.com/nbd-wtf/go-nostr/blob/8a540998b922600669774fe38c55205914ae79a5/connection.go#L59) as the source of memory consumption but I'd assume this would affect other if that was the case - so I must be doing something wrong.

**Comment by fiatjaf** [comment]
Since you have pprof installed can you get the list of all goroutines that are running?

`curl -sK -v http://localhost:7447/debug/pprof/goroutine?debug=2 > goroutines.out`

That should give us exactly where a bunch of them are halted.

Also please make sure you're using the latest go-nostr as I fixed a (rather stupid) bug related to this very recently.

**Comment by bndw** [comment]
https://gist.github.com/bndw/2a6b83305cbbf27a968678cf4485d6a3

I'm seeing over 100 matches for `github.com/nbd-wtf/go-nostr.(*Relay).Connect.func1()`, many of which say multiple minutes. This seems to imply user error on my part - the client is sending a lot of queries quickly and my code establishes a fresh connection each time. This feels like a perf bug at best - do you think that's the root of the memory leak? I could cache the relay connections in memory instead.

**Comment by fiatjaf** [comment]
Yes, the pool is meant to be like a singleton in your program, it will keep a single connection to each relay and use that same connection for everything.

**Comment by fiatjaf** [comment]
Thank you for the goroutines breakdown file. I didn't see any hint of goroutine leak in that. All the goroutines that are halted are either waiting for a new message to come from the relay or for a context to be done so they can close themselves and stuff like that.

**Comment by bndw** [comment]
I appreciate your help working through this!
