### ISSUE TITLE
tags in filter are not JSON-serializable/deserializable

### ISSUE THREAD

**Issue by rolznz** [nbd-wtf/go-nostr#128]
https://github.com/nbd-wtf/go-nostr/blob/master/filter.go#L16

Is there any good reason for this? it means the filter struct cannot be easily used

**Comment by fiatjaf** [comment]
There is a custom Marshaler for the `Filter` struct made with easyjson. It wouldn't work with default `json:""` tags-based serializers. We should actually remove these annotations from the struct.
