### ISSUE TITLE
Event JSON tags

### ISSUE THREAD

**Issue by ice-dionysos** [nbd-wtf/go-nostr#133]
I see that all JSON tags were removed here https://github.com/nbd-wtf/go-nostr/commit/2bf6c87b45b7ea765b16ca4ef6d218fcd374fbb3

Any reason why? Could we bring them back?

Thanks.

**Comment by fiatjaf** [comment]
They were not being used, as the `Event` and `Filter` types implement custom JSON marshalers and unmarshalers. Is that not working for you?
