### ISSUE TITLE
nip46: possibly duplicated code

### ISSUE THREAD

**Issue by sebdeveloper6952** [nbd-wtf/go-nostr#152]
Does this look like duplicated code to you guys? Maybe the second ocurrence was supposed to be related to nip44?

[Code starts here](https://github.com/nbd-wtf/go-nostr/blob/d29025e958231e9950d046010423dee4975fb3f1/nip46/dynamic-signer.go#L102). Blocks in question start at lines 102 and 107

**Comment by fiatjaf** [comment]
Oops.
