### ISSUE TITLE
Why pool.add(relay) returns a channel as error

### ISSUE THREAD

**Issue by arejula27** [nbd-wtf/go-nostr#16]
I dont understand why a channel is returned when can be returned a error. In the commit was written something about a helper function and logic. What that these refer?

**Comment by fiatjaf** [comment]
Can you please post links to the commit and the parts of the code you're referring to?

**Comment by arejula27** [comment]
Is the commit 14e81a756acd0b2b20061cb791f55f9f2d4f83af. Line 63 of the relaypool,go file. The function Add() chnage its return type

**Comment by fiatjaf** [comment]
That's not a channel as error, it's a channel of errors. Channels are primitive Go types: https://gobyexample.com/channels

**Comment by arejula27** [comment]
yes, i undestand that, but why?  The channel is  created inside the func so is not reuse as i see, only send nil or one error.

**Comment by arejula27** [comment]
maybe the idea is that the channel is on the (r *RelayPool)  object? so all the functions send the errors using the chan?

**Comment by stanstacks** [comment]
Because the show isn't over just because the function has returned. Subscriptions run in a goroutine, any errors from the relay can come in at any time while the subscription is still open. A channel is the logical way to handle this.

**Comment by fiatjaf** [comment]
Callbacks!
