### ISSUE TITLE
Extra padding incompatibility

### ISSUE THREAD

**Issue by WesVleuten** [nbd-wtf/go-nostr#21]
On the implementation of [nip04](https://github.com/nbd-wtf/go-nostr/blob/master/nip04/nip04.go#L70) padding is used.

This seems to be causing incompatibility with other clients like Damus.

In the [spec](https://github.com/nostr-protocol/nips/blob/master/04.md) of nip04 there doesn't seem to be a definition of padding.

Would it be possible to remove the padding, or at least have it be optional?

If agreed, I can submit a PR with a fix

**Comment by fiatjaf** [comment]
My understanding is that it is not possible to implement AES-CBC without padding. How is Damus doing it?

**Comment by WesVleuten** [comment]
I think the problem is the extra padding. It might be the extra padding it's not understanding

**Comment by WesVleuten** [comment]
I'm looking into Damus right now. As I said before, it might just be on their side

**Comment by fiatjaf** [comment]
Makes sense that the extra padding is breaking them, although it should be supported. It makes sense to remove it from here. Please open a PR.
