### ISSUE TITLE
problem: valid event signatures are being rejected as invalid

### ISSUE THREAD

**Issue by stanstacks** [nbd-wtf/go-nostr#28]
Valid events are being dropped here: https://github.com/nbd-wtf/go-nostr/blob/bb1138a2fa2dad5d329bf149a280814f9e9bd8af/relay.go#L144

For some reason Signature.Verify in `github.com/btcsuite/btcd/btcec/v2` returns false on some signatures that are actually valid.

Here's a smattering of event IDs that were reported as an invalid sig:
```
31acf56113720da6fe4aff4f2339294fa96addee134609180286c184e74641d1
180c99be0a40eee4dce93aa29cd03586d2b58468d13f7862dd403534404cd937
190c840ad07ab6cecac6cc7acb4773572da548609be817d680dd9007946113ca
b3a6b874c615bfad7b2fb207372202bf51b70cd58c9300a0c269c94fc54cec69
b1483e40f1bbaeafe88bb07ff96dfe5a0838c4adddbc2c6336b47dd4b1860cd9
```

Nostr army knife validates them as valid.

**Comment by barkyq** [comment]
see also:
note1z5309a387nja69gglucp9us64ecznzp6jqgwgar8f5fde4fzc97qtarjkj
my hunch is that it is a problem with the serialization used in fastjson...

**Comment by barkyq** [comment]
this string is not signing properly for me:
"Oh jack…🤦🏻‍♂️ \nThe inability to delete messages is the best!"

my note gets rejected when I try to use example/example.go (but it works for normal strings)

**Comment by barkyq** [comment]
s‍eems to be certain unicode characters. 

for instance, this note fails (but if I change `r` to say, 100, then it won't fail)

``` go
sk := nostr.GeneratePrivateKey()
pub, _ := nostr.GetPublicKey(sk)
url := "wss://nostr.zebedee.cloud"
relay, e := nostr.RelayConnect(context.Background(), url)
if e != nil {
	panic(e)
}
var r rune = 142	
ev := nostr.Event{
	PubKey:    pub,
	CreatedAt: time.Now(),
	Kind:      1,
	Tags:      nil,
	Content:   "\n" + string(r),
}
fmt.Println(strconv.Quote(ev.Content))
ev.Sign(sk)
fmt.Println("published to", url, relay.Publish(context.Background(), ev))
```
I include the `\n` as this forces `fastjson` to quote the string, which seems to be where the issue lies (but not every quoted string fails...)

**Comment by barkyq** [comment]
re-writing `Serialize()` in`event.go` to:
``` go
func (evt *Event) Serialize() []byte {
	// the serialization process is just putting everything into a JSON array
	// so the order is kept
	var tmp_event []interface{}

	// version: 0
	tmp_event = append(tmp_event, 0)

	// pubkey
	tmp_event = append(tmp_event, evt.PubKey)

	// created_at
	tmp_event = append(tmp_event, int(evt.CreatedAt.Unix()))

	// kind
	tmp_event = append(tmp_event, evt.Kind)

	// tags
	t := make([][]string, 0)
	for _, tag := range evt.Tags {
		t = append(t, []string(tag))
	}
	tmp_event = append(tmp_event, t)

	// content
	tmp_event = append(tmp_event, evt.Content)
	bytes, err := json.Marshal(tmp_event)
	if err != nil {
		panic(err)
	}
	return bytes
}
```
seems to fix the issue, but is probably quite a bit more inefficient than using fastjson...

**Comment by fiatjaf** [comment]
Nice catch.

**Comment by barkyq** [comment]
using `json.Marshal` doesn't fix the problem, unfortunately...
seems like `json.Marshal` will marshal `"&"` to `"\u0026"` (which is not what "wss://nostr.zebedee.cloud" is expecting).

**Comment by barkyq** [comment]
with` a bit more research, I learned that you can turn off HTML escaping with `encoding/json` package.
this version of `(* event) Serialize()` seems to work:

``` go
func (evt *Event) Serialize() []byte {
	// the serialization process is just putting everything into a JSON array
	// so the order is kept
	var tmp_event []interface{}

	// version: 0
	tmp_event = append(tmp_event, 0)

	// pubkey
	tmp_event = append(tmp_event, evt.PubKey)

	// created_at
	tmp_event = append(tmp_event, int(evt.CreatedAt.Unix()))

	// kind
	tmp_event = append(tmp_event, evt.Kind)

	// tags
	t := make([][]string, 0)
	for _, tag := range evt.Tags {
		t = append(t, []string(tag))
	}
	tmp_event = append(tmp_event, t)

	// content
	tmp_event = append(tmp_event, evt.Content)

	// marshal, need to use a json.Encoder so that EscapeHTML can be turned off.
	buf := bytes.NewBuffer(nil)
	enc := json.NewEncoder(buf)
	enc.SetEscapeHTML(false)
	enc.Encode(tmp_event)

	// encode adds a newline character as the last byte, need to remove
	return buf.Bytes()[:buf.Len()-1]
}
```

**Comment by barkyq** [comment]
@stanstacks is the issue fixed for you?

**Comment by barkyq** [comment]
OK seems to be fixed. Let's close this! Then there will be no issues :)

**Comment by fiatjaf** [comment]
Wow, such a good library!
