### ISSUE TITLE
example in README does not work

### ISSUE THREAD

**Issue by barkyq** [nbd-wtf/go-nostr#32]
`nostr.NewRelayPool()` does not seem to be a defined function?

also the added contexts everywhere... I am a bit confused, perhaps the new introductory example can explain a bit what you had in mind for those. I just use `context.Background()` everywhere.

**Comment by fiatjaf** [comment]
Just use `context.Background()` everywhere and you will be fine.

**Comment by barkyq** [comment]
fixed with pull request #34
