### ISSUE TITLE
Subscription not unsubbed when publishing an event

### ISSUE THREAD

**Issue by cj-chua** [nbd-wtf/go-nostr#35]
When a relay publishes an event, it immediately subscribes to the event to find out if the event was indeed sent. The subscription is not "removed" after the deed is done
```//go
// relay.go    func Publish()

sub := r.Subscribe(ctx, Filters{Filter{IDs: []string{event.ID}}})
defer sub.Unsub()   <<---- this line is missing? --------
for {
        select {
        case receivedEvent := <-sub.Events:
	        if receivedEvent.ID == event.ID {
		        // we got a success, so update our status and proceed to return
		        status = PublishStatusSucceeded
		        return status
	        }
        case <-ctx.Done():
	        // return status as it was
	        // will proceed to return status as it is
	        // e.g. if this happens because of the timeout then status will probably be "failed"
	        //      but if it happens because okCallback was called then it might be "succeeded"
	        return status
        }
}
```
This is probably a minor issue. I'm trying to understand the codebase better and thought I would get some clarification on this issue to make sure that my understanding is correct

**Comment by fiatjaf** [comment]
Good catch! Can you send a PR fixing this?

**Comment by cj-chua** [comment]
Yes will do.

I'm still digging cause my program is still crashing intermittently. My guess is that there's a race condition going on with `Unsub`..., but I could be calling stuff incorrectly too

I'm getting `panic: send on closed channel` in relay.go Connect() under `case "EVENT":`
```
if !subscription.stopped {
		subscription.Events <- event
}
```

In subscription.go, we close the channel before setting the field `stopped = true`. My hypothesis is that between the time where `close(sub.Events)` and `sub.stopped = true` is called, `subscription.stopped` is evaluated? `if !subscription.stopped` evaluation should be wrapped in a mutex?
```
func (sub *Subscription) Unsub() {
	sub.mutex.Lock()
	defer sub.mutex.Unlock()

	sub.conn.WriteJSON([]interface{}{"CLOSE", sub.id})
	if sub.stopped == false && sub.Events != nil {
		close(sub.Events)
	}
	sub.stopped = true
}
```

**Comment by cj-chua** [comment]
Update: making this change seems to have fixed the issue
```go
subscription.mutex.Lock()
if !subscription.stopped {
		subscription.Events <- event
}
subscription.mutex.UnLock()
```
```

**Comment by barkyq** [comment]
> When a relay publishes an event, it immediately subscribes to the event to find out if the event was indeed sent. The subscription is not "removed" after the deed is done.

I believe the subscription is removed, because of the `defer cancel()` in the `Publish` function. The subscription is fired with a context which gets canceled, which closes the `ctx.Done()` channel.

``` go
func (sub *Subscription) Fire(ctx context.Context) {
	message := []interface{}{"REQ", sub.id}
	for _, filter := range sub.Filters {
		message = append(message, filter)
	}

	sub.conn.WriteJSON(message)

	// the subscription ends once the context is canceled
	go func() {
		<-ctx.Done()
		sub.Unsub()
	}()
}
```

**Comment by barkyq** [comment]
@cj-chua good to close?

**Comment by cj-chua** [comment]
yes sir!
