### ISSUE TITLE
relay.Subscribe only returning a single event

### ISSUE THREAD

**Issue by cj-chua** [nbd-wtf/go-nostr#36]
Running the latest code, relay.Subscribe only returns a single event. The filter set is the following
```go
now := time.Now()
sub := relay.Subscribe(context.Background(), nostr.Filters{
        nostr.Filter{
	        Kinds: []int{nostr.KindTextNote},
	        Since: &now,
        },
})
```

Unfortunately I'm can't seem to drill down what is causing the issue. Anyone else having the same issue?

**Comment by fiatjaf** [comment]
`Since: now` will only return events going forward, nothing from the past. Is that what you want?

You mean only a single event will be returned going forward and nothing else after that?

Could be a channel buffer thing causing everything to halt. You must read from the channel.

**Comment by cj-chua** [comment]
Here is the full code
```go
relay, err := nostr.RelayConnect(context.Background(), "wss://nostr-relay.untethr.me")
if err != nil {
	panic(err)
}
since := time.Now().Add(-5 * time.Hour)
sub := relay.Subscribe(context.Background(), nostr.Filters{
	nostr.Filter{
		Kinds: []int{nostr.KindTextNote},
		Since: &since,
	},
})
go func() {
	for ee := range sub.Events {
		log.Printf("%v", ee.Content)
	}
}()
time.Sleep(time.Second * 180)
sub.Unsub()
return
```

I have found the issue... This code snippet from #35  is somehow causing the code to hang
```go
subscription.mutex.Lock()
if !subscription.stopped {
	subscription.Events <- event
}
subscription.mutex.UnLock()
```

Any ideas on how to proceed? If the mutex is not in place I get a `send on closed channel` error

**Comment by barkyq** [comment]
when I run your program, I get many many events returned, seems to work as expected

**Comment by cj-chua** [comment]
I think I have to dig deeper into my code. Essentially what I'm doing is just subscribing to a bunch of relays to get data, process them, and then publishing the processed data via another set of relays. The `send on closed channel` panic comes from the publishing part

As per this [comment](https://github.com/nbd-wtf/go-nostr/issues/35#issuecomment-1382953855), would you say it is a scenario that will likely happen?

**Comment by barkyq** [comment]
hm... well I was getting data races when sub.Unsub() was called. I submitted a pull request which appears to fix the data race issue. with the modified relay.go package, I get no data races. I also modified your script slightly...

```go
func main() {
	relay, err := nostr.RelayConnect(context.Background(), "wss://nostr-relay.untethr.me")
	if err != nil {
		panic(err)
	}
	since := time.Now().Add(-5 * time.Hour)
	ctx, cancel := context.WithTimeout(context.Background(), 180*time.Second)
	sub := relay.Subscribe(ctx, nostr.Filters{
		nostr.Filter{
			Kinds: []int{nostr.KindTextNote},
			Since: &since,
			Limit: 100,
		},
	})
	go func() {
		<-sub.EndOfStoredEvents
		cancel()
	}()
	for ee := range sub.Events {
		fmt.Println(ee.CreatedAt.String())
	}
}
```

**Comment by cj-chua** [comment]
#37
