### ISSUE TITLE
(NIPS-04) Encrypted Direct Message Example 

### ISSUE THREAD

**Issue by bobbaker6667** [nbd-wtf/go-nostr#46]
Hi, could you provide an example of sending and receiving Encrypted Direct Messages to a public key (NIPS-04)?

https://github.com/nostr-protocol/nips/blob/master/04.md

**Comment by fiatjaf** [comment]
Here is an example: https://github.com/nbd-wtf/go-nostr/blob/92c0143762f349d1ab9316f8eb622b54dddd486a/nip04/nip04_test.go#L8-L25

**Comment by bobbaker6667** [comment]
Thanks appreciate it
