### ISSUE TITLE
Question on websocket 

### ISSUE THREAD

**Issue by cj-chua** [nbd-wtf/go-nostr#47]
Websocket connections to some relays are closed after a minute of inactivity(I'm seeing it with wss://nostr.oxtr.dev, wss://relay.stoner.com, etc). What should I do if I want to keep the connection alive as long as possible?

What I have in mind is to listen to the connectionError channel and call Connect again when connection breaks (and it's uninitiated by us). Is that the right approach?

**Comment by fiatjaf** [comment]
Maybe approach these relay owners to tell them about it? Otherwise not use them since they're buggy.

**Comment by cj-chua** [comment]
For my use case, I have a bot that needs to keep relay connections alive even when there is long periods of inactivity. So even if relays don't terminate after a minute of inactivity upon connection establishment, I've noticed that the connections alive slowly decreases over time (they just start to drop off one by one)

Right now I'm going to experiment wrapping nostr.Relay in some sort of reconnection logic and see how that goes
