### ISSUE TITLE
Support OrbitDB

### ISSUE THREAD

**Issue by TheRook** [nbd-wtf/go-nostr#57]
What would you like to be added:
Consider using https://github.com/berty/go-orbit-db as a backend to expose a nostr provider as a Kademlia service. Kademlia implemented with libp2p is one of the most mature p2p networks, designed over 20 years ago it has scaled up to hundreds of millions of nodes and is the network behind Ethereum, IPFS and Magnet BitTorrent links.

Why is this needed:
It allows nostr to be run as a federated dapp and hosted by a community.
https://www.youtube.com/watch?v=cC-tXnMyiBc

**Comment by barkyq** [comment]
Interesting but don't know if this library is the right place to implement storage backends... Might make more sense at something like https://github.com/fiatjaf/relayer?

**Comment by fiatjaf** [comment]
Yes, but do not create a ticket asking for this there either, just take these libraries and build your OrbitDB solution.

**Comment by TheRook** [comment]
I wouldn't build anything on the current nostr because the protocol is trivial to DoS - everyone will have to move to a new protocol eventually, and Kademila which runs Orbit and IPFS was designed to prevent DoS.

**Comment by fiatjaf** [comment]
I don't understand why you took your time to write this issue.

**Comment by barkyq** [comment]
Voting to close the issue.
