### ISSUE TITLE
nip04 Decrypt method paniced

### ISSUE THREAD

**Issue by cj-chua** [nbd-wtf/go-nostr#64]
In file nip04/nip04.go:

`panic: runtime error: slice bounds out of range [:-193]`

this is the offending line
```
105            message := string(plaintext[0 : len(plaintext)-padding])
```

the encrypted string that triggers this to happen
`e2FAnpPXoAyQfA26zke60w==?iv=DWb3UYIqz4U/XLaNAkMGiA==`

Any more info I should provide?

**Comment by fiatjaf** [comment]
I imagine the solution is to just check the lengths?
