### ISSUE TITLE
nip05 add CheckRedirect for http.Client

### ISSUE THREAD

**Issue by zach030** [nbd-wtf/go-nostr#66]
As mentioned in NIP-05 part [security-constraints](https://github.com/nostr-protocol/nips/blob/master/05.md#security-constraints), It's better to add `CheckRedirect` for http Client option to restrict redirect from server.
```go
	client := &http.Client{
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse // return error to prevent redirect
		},
	}
```

**Comment by fiatjaf** [comment]
I agree. Can you open a pull request?

**Comment by zach030** [comment]
Sure, I will open a pull request
