### ISSUE TITLE
Question on string escape

### ISSUE THREAD

**Issue by metacatdud** [nbd-wtf/go-nostr#73]
Why did you opt for a custom build `escapeString` over the native one?
https://pkg.go.dev/strconv#AppendQuote

I tested it out and it seems to produce the same result 

Test string 
```go
message := `{"msg":"Hello Alice! How are you?", /"bad/": "field"}`
```

```shell
ESCAPED escapeString :"{\"msg\":\"Hello Alice! How are you?\", /\"bad/\": \"field\"}"
```
```shell
ESCAPED strconv.AppendQuote :"{\"msg\":\"Hello Alice! How are you?\", /\"bad/\": \"field\"}"
```

Thanks

**Comment by fiatjaf** [comment]
I don't remember, I didn't even remember having written a custom `escapeString`, but I think this is outdated now, right? The JSON encoders were replaced. Sorry, I missed this issue at the time.
