### ISSUE TITLE
Tag scan

### ISSUE THREAD

**Issue by metacatdud** [nbd-wtf/go-nostr#77]
Here: https://github.com/nbd-wtf/go-nostr/blob/master/tags.go#L117

Function 
```go
func (t *Tags) Scan(src any) error {
	var jtags []byte = make([]byte, 0)

	switch v := src.(type) {
	case []byte:
		jtags = v
	case string:
		jtags = []byte(v)
	default:
		return errors.New("couldn't scan tags, it's not a json string")
	}

	json.Unmarshal(jtags, &t)
	return nil
}
```

It's unclear how the parameter should look like because the `Unmarshal` error is never handled 
My guess at a glance is that this function is never used or can someone help me understand?

**Comment by fiatjaf** [comment]
It's used to scan tags from a database on https://github.com/fiatjaf/relayer. It expects them to be written all together as a JSON string.

**Comment by metacatdud** [comment]
Ok! Got it. I wasn't able to find anywhere in [relayer](https://github.com/fiatjaf/relayer) how is it used, but is ok I guess

**Comment by fiatjaf** [comment]
It's used under the hood, as part of the [`sql.Scanner`](https://pkg.go.dev/database/sql#Scanner) interface. Go is confusing.
