### ISSUE TITLE
Missing package filters and event in module v0.6.2

### ISSUE THREAD

**Issue by theRescuer** [nbd-wtf/go-nostr#9]
Hi,
Trying to define the handlers for relayer I get stuck when 
~/go/src/relayer$ go get github.com/fiatjaf/go-nostr/filter
go get: module github.com/fiatjaf/go-nostr@upgrade found (v0.6.2), but does not contain package github.com/fiatjaf/go-nostr/filter

Same goes for
~/go/src/relayer$ go get github.com/fiatjaf/go-nostr/event.

Any advice?

**Comment by fiatjaf** [comment]
Tons of breaking changes. Did you update relayer?

**Comment by barkyq** [comment]
seems like this issue can be closed
