### ISSUE TITLE
v0.17.0 can no longer post to wss://relay.damus.io

### ISSUE THREAD

**Issue by marcopeereboom** [nbd-wtf/go-nostr#91]
It seems that the lib can no longer post to `relay.damus.io` when using commit: 0a3e898c2f62cdf1e8cdfa58d1e07e8ed104190b or c42059f4b49d01e056aea4a6ae8a0603926521ed.

Event is simple (somewhat simplified for readability):
```
        ev := nostr.Event{
                PubKey:    n.public,
                CreatedAt: time.Now(),
                Kind:      nostr.KindTextNote,
                Tags:      nil,
                Content:   msg,
        }
        ev.Sign(n.private)
        result, err := r.Publish(ctx, ev)
        if err != nil {
                n.printf("publishing error %v: %v\n", r, err)
        }
        if result == nostr.PublishStatusFailed {
                n.printf("could not send: %v\n", r)
        }
```

This ends up traveling through `nostr.PublishStatusFailed` path like so: `could not send: wss://relay.damus.io` and the damus client does indeed not receive the message.

Running the same code (minus the time modifications required by v0.17.0) works fine.

Was hoping someone would know what is up before I spend a bunch of time digging through the code.

**Comment by fiatjaf** [comment]
I just published this with https://github.com/fiatjaf/nak (which is using v0.18.7):

![2023-06-13-092626_609x132_scrot](https://github.com/nbd-wtf/go-nostr/assets/1653275/16f9db1d-1381-4137-aace-b0ca70b60dd6)

**Comment by fiatjaf** [comment]
You are missing the tags.

**Comment by fiatjaf** [comment]
Will add a clearer error for this case.

**Comment by fiatjaf** [comment]
5bbb6ba05b7e0aab44438065b319e6adbc08308c

**Comment by fiatjaf** [comment]
Optional means they are an empty array.

**Comment by marcopeereboom** [comment]
Wouldn't it then not make more sense to define tags as an array instead of a pointer?

**Comment by fiatjaf** [comment]
Arrays are pointers.
