### ISSUE TITLE
ParseMessage panics on invalid input

### ISSUE THREAD

**Issue by boreq** [nbd-wtf/go-nostr#92]
Calling `ParseMessage` with invalid input triggers a panic.

```
import (
	"github.com/nbd-wtf/go-nostr"
	"testing"
)

func TestPanic(t *testing.T) {
	nostr.ParseMessage([]byte("invalid,input"))
}
```

**Comment by fiatjaf** [comment]
Please don't create these issues if you are already going to submit a fix. Just submit the fix directly!
